export const ProductsActionTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FALIURE: "FETCH_PRODUCTS_FALIURE",
  DESERIALIZE_PRODUCTS: "DESERIALIZE_PRODUCTS",
};
